default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Ryugaku_info_2_development

test:
  <<: *default
  database: Ryugaku_info_2_test

production:
  <<: *default
  database: Ryugaku_info_2_production
  username: Ryugaku_info_2
  password: <%= ENV['Ryugaku_info_2_DATABASE_PASSWORD'] %>