Bookd.create(title: 'フィリピン学校' ,name: 'フィリピン学校1')
Bookd.create(title: 'フィリピン学校' ,name: 'フィリピン学校2')
Bookd.create(title: 'フィリピン学校' ,name: 'フィリピン学校3')
Bookd.create(title: 'フィリピン学校' ,name: 'フィリピン学校4')
Bookd.create(title: 'フィリピン学校' ,name: 'フィリピン学校5')
Bookd.create(title: 'フィリピン学校' ,name: 'フィリピン学校6')
Bookd.create(title: 'フィリピン学校' ,name: 'フィリピン学校7')